server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:13333/kodn?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true&useSSL=false'
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

